class AppLang {
  static const Map<String, String> _english = {
    'greeting': 'Hello',
    'request': 'Request',
    // Home ================================================
    'home_today': 'Daily',
    'home_monthly': 'Monthly',
    'home_request': 'Request',
    'home_review': 'Review',
    'home_total_working_hours': 'Total Working Hours',
    'home_grade_received': 'Grade Received',
    'home_scan': 'Scan',
    'home_daily': 'Daily',
    'home_evaluation': 'Evaluation',
    'home_personal_info': 'Personal Info',
    'home_job': 'Job',
    'home_salary': 'Salary',
    'home_id_card': 'ID Card',
    'home_document': 'Document',
    'home_no_name': 'No Name',
    'home_no_department': 'No Department',
    'hour': 'H',
    'minute': 'M',
    // About ================================================
    'about_system': 'About System',
    'about_rule': 'Rule',
    'about_daily_scan': 'Daily Scan',
    'about_face_scanner': 'Face Scanner',
    'about_working_hours': 'Working Hours',
    'about_number_of_days': 'Number of Days',
    'about_total_hours': 'Total Hours',
    'about_scan_in': 'Scan In',
    'about_scan_out': 'Scan Out',
    'about_note': 'Note',
    'about_active': 'Active',
    'about_hours': 'Hours',
    'about_day': 'Day',
    'about_week': 'Week',
    'about_lunch_break': 'Lunch Break Exemption 2 Hours',
    // Layout ================================================
    'layout_home': 'Home',
    'layout_about': 'About',
    'layout_holiday': 'Holiday',
    'layout_other': 'Other',
    // User Infor ================================================
    'user_info_name': 'Name',
    'user_info_sex': 'Sex',
    'user_info_phone': 'Phone Number',
    'user_info_email': 'Email',
    'user_info_card_id': 'ID Card Number',
    'user_info_date_of_birth': 'Date of Birth',
    'user_info_place_of_birth': 'Place of Birth',
    'user_info_current_address': 'Current Address',
    'user_info_personal_info': 'Personal Information',
    'user_info_family': 'Family and Relatives',
    'user_info_family_add': 'Add Family or Relatives',
    'user_info_language_add': 'Add Language',
    'user_info_education_add': 'Add Education',
    'user_info_language': 'Langauge',
    //User Info Update =======================================
    'user_info_update': 'Update User Information',
    'user_info_salute': 'Salute',
    'user_info_kh_name': 'Khmer Name',
    'user_info_en_name': 'English Name',
    'user_info_male': 'Male',
    'user_info_female': 'Female',
    'user_info_province': 'Province',
    'user_info_district': 'District',
    'user_info_commune': 'Commune',
    'user_info_village': 'Village',
    'user_info_street': 'Street',
    'user_info_number': 'Home Number',
    'user_info_note': 'Note',
    'user_info_family_update':'Update Family',

    // Add Relative
    'relative_type':'Relative Type',
    'female':'Female',
    'dob':'Date Of Birth',
    'job':'Job',
    'work_place':'Work Place',
    'please enter name_en':'Please Enter English Name',
    'please enter name_kh':'Please Enter Khmer Name',
    'please select relative type':'Please Select Relative Type',
    // Add User Education
    'Please select certificate type': 'Please select certificate type',
    'Please select education level': 'Please select education level',
    'Please select education type': 'Please select education type',
    'Start Date is required':'Please select enroll date',
    'Start DateOut is required':'Please select graduate date',
    'create': 'Create',
    'update': 'Update',
    'delete':'Delete',
    'Confirm Delete':'Confirm Delete',
    'Are you sure to delete':'Are you sure to delete',
    'deleted success':'Deleted Success',
    'Select Education Type':'Select Education Type',
    'user_education_type' :'Type',
    'user_educationLevel':'User Education Level',
    'certificate':'Certificate',
    'majors':'Majors',
    'school':'School',
    'school place':'Place of Study',
    'enroll date':'Enroll Date',
    'graduated date':'Graduated Date',
    'Are you sure to create':'Are you sure to create?',
    // Add User Language
    'speaking level': 'Speaking Level',
    'choose language': 'Choose Language',
    'please select language': 'Please Select Language',
    'please select level': 'Please Select Level',
    'reading level':'Reading Level',
    'writting level':'Writting Level',
    'listenning level':'Listenning Level',
    'user_language_level':'Language Level',
    // Work 
    'work':'Work',
    'id_number': 'ID Number',
    'staff_card_number':'Staff Card Number',
    'appointed_at':'Appointe Date',
    'start_working_at':'Start Working Date',
    'organization':'Organization',
    'position':'Position',
    'department':'Department',
    'staff_type':'Staff Type',
    'rank_position':'Rank Possition',
    'office':'Office',
    'framework_category':'Frame Work Category',
    'salary_rank_group':'Salary Rank Group',
    'salary_rank_type':'Salary Rank Type',
    'upgraded_salary_rank_at':'Upgraded Salary Rank At',
    'certificate_type':'Certificate',
    'major':'Major',
    'graduated_at':'Graduated At',
    'prakas_number':'Prakas Number',
    'prakas_at':'Prakas At',
    'skill':'Skill',
    'work_experience':'Work Experience',
    'work_experience_add':'Add Work Experience',
    'medals_add':'Add Medal',
    'medals':'Medal'
    // Layout ================================================
  };

  static const Map<String, String> _khmer = {
    'greeting': 'សួស្តី',
    'request': 'សំណើរ',
    // Home ================================================
    'home_today': 'ថ្ងៃនេះ',
    'home_monthly': 'ប្រចាំខែ',
    'home_request': 'ស្នើសុំ',
    'home_review': 'ត្រួតពិនិត្យ',
    'home_total_working_hours': 'សរុបម៉ោងធ្វើការ',
    'home_grade_received': 'ទទួលនិទ្ទេស',
    'home_scan': 'ស្កេន',
    'home_daily': 'ប្រចាំថ្ងៃ',
    'home_evaluation': 'វាយតម្លៃ',
    'home_personal_info': 'ព័ត៌មានផ្ទាល់ខ្លួន',
    'home_job': 'ការងារ',
    'home_salary': 'ប្រាក់បៀវត្សរ៍',
    'home_id_card': 'ប័ណ្ណសម្គាល់ខ្លួន',
    'home_document': 'ឯកសារ',
    'home_no_name': 'មិនមានឈ្មោះ',
    'home_no_department': 'មិនមានផ្នែក',
    'hour': 'ម៉ោង',
    'minute': 'នាទី',
    // About ================================================
    'about_system': 'អំពីប្រព័ន្ធ',
    'about_rule': 'អនុក្រឹត',
    'about_daily_scan': 'ការស្កេនប្រចាំថ្ងៃ',
    'about_face_scanner': 'ម៉ាស៊ីនស្កេនមុខ',
    'about_working_hours': 'ម៉ោងធ្វើការ',
    'about_number_of_days': 'ចំនួនថ្ងៃ',
    'about_total_hours': 'ចំនួនម៉ោង',
    'about_scan_in': 'ស្កេនចូល',
    'about_scan_out': 'ស្កេនចេញ',
    'about_note': 'សម្គាល់',
    'about_active': 'សកម្ម',
    'about_hours': 'ម៉ោង',
    'about_day': 'ថ្ងៃ',
    'about_week': 'សប្តាហ៍',
    'about_lunch_break': 'លើកលែងម៉ោងបាយថ្ងៃត្រង់ 2 ម៉ោង',
    // Layout ================================================
    'layout_home': 'ទំព័រដើម',
    'layout_about': 'អំពីប្រព័ន្ធ',
    'layout_holiday': 'ឈប់សម្រាក',
    'layout_other': 'ផ្សេងៗ',
    // User Infor ================================================
    'user_info_name': 'ឈ្មោះ',
    'user_info_sex': 'ភេទ',
    'user_info_phone': 'លេខទូរស័ព្ទ',
    'user_info_email': 'អ៊ីមែល',
    'user_info_card_id': 'អត្តសញ្ញាណប័ណ្ណ',
    'user_info_date_of_birth': 'ថ្ងៃខែឆ្នាំកំណើត',
    'user_info_place_of_birth': 'ទីកន្លែងកំណើត',
    'user_info_current_address': 'អាសយដ្ឋានបច្ចុប្បន្ន',
    'user_info_personal_info': 'ព័ត៌មានផ្ទាល់ខ្លួន',
    'user_info_family': 'គ្រួសារនិងសាច់ញាតិ',
    'user_info_family_add': 'បន្ថែមគ្រួសារនិងសាច់ញាតិ',
    'user_info_language_add': 'បន្ថែមកម្រិតភាសា',
    'user_info_education_add': 'បន្ថែមការសិក្សា',
    'user_info_language': 'ភាសា',
    // User Info Update ======================
    'user_info_update': 'កែប្រែព័ត៌មានផ្ទាល់ខ្លួន',
    'user_info_salute': 'ងារ',
    'user_info_kh_name': 'ឈ្មោះជាភាសាខ្មែរ',
    'user_info_en_name': 'ឈ្មោះជាភាសាអង់គ្លេស',
    'user_info_male': 'ប្រុស',
    'user_info_female': 'ស្រី',
    'user_info_province': 'ខេត្ត/ក្រុង',
    'user_info_district': 'ស្រុក/ខណ្ឌ/ក្រុង',
    'user_info_commune': 'ឃុំ/សង្កាត់',
    'user_info_village': 'ភូមិ',
    'user_info_street': 'ផ្លូវ',
    'user_info_number': 'ផ្ទះលេខ',
    'user_info_note': 'កំណត់សម្គាល់',
    'user_info_family_update':'កែប្រែសាចញាតិ',
    //Add Relative 
    'relative_type':'ត្រូវជា',
    'male':'ប្រុស',
    'female':'ស្រី',
    'dob':'ថ្ងៃខែឆ្នាំកំណើត',
    'work_place':'ស្ថាប័ន',
    'please enter name_en':'សូមបញ្ចូលឈ្មោះជាអក្សរឡាតាំង',
    'please enter name_kh':'សូមបញ្ចូលឈ្មោះជាភាសារខ្មែរ',
    'please select relative type':'សូមជ្រើសរើសប្រភេទសាច់ញ្ញាតិ',
    'job':'មុខរបរ',
    // Add User Education
    'Please select education level': 'សូមជ្រើសរើសកម្រិតការសិក្សា',
    'Please select certificate type': 'សូមជ្រើសរើសប្រភេទសញ្ញាបត្រ',
    'Please select education type': 'សូមជ្រើសរើសប្រភេទការសិក្សា',
    'Start Date is required':'សូមជ្រើសរើសថ្ងៃចូលសិក្សា',
    'Start DateOut is required':'សូមជ្រើសរើសថ្ងៃបញ្ចប់ការសិក្សា',
    'create': 'បង្កើត',
    'update': 'កែប្រែ',
    'delete':'លុប',
    'Confirm Delete':'លុប',
    'Are you sure to delete':'តើអ្នកប្រកដទេថាចង់លុប',
    'deleted success':'លុប​បានជោគជ័យ',
    'Select Education Type':'ជ្រើសរើសប្រភេទការសិក្សា',
    'user_education_type':'ប្រភេទ',
    'user_educationLevel':'កម្រិតការសិក្សា',
    'certificate':'សញ្ញាបត្រ',
    'majors':'ជំនាញ',
    'school':'គ្រឹះស្ថានសិក្សា',
    'school place':'ទីកន្លែងសិក្សា',
    'enroll date':'ថ្ងៃចូលសិក្សា',
    'graduated date':'ថ្ងៃបញ្ចប់',
   'Are you sure to create':'តើអ្នកប្រកដទេថាចង់បង្កើត?',
    //Add User Language
    'speaking level': 'កម្រិតនិយាយ',
    'please select level': 'សូមជ្រើសរើសកម្រិត',
    'choose language': 'ជ្រើសរើសភាសា',
    'please select language': 'សូមជ្រើសរើសភាសា',
    'reading level':'កម្រិតអាន',
    'writting level':'កម្រិតសរសេរ',
    'listenning level':'កម្រិតស្ដាប់',
    'user_language_level':'កម្រិតភាសា',

    //Work 
    'work': 'ការងារ',
    'id_number':'អត្តលេខ',
    'staff_card_number':'លេខកាត',
    'appointed_at':'ថ្ងៃតែងតាំង',
    'start_working_at':'ថ្ងៃចូលបម្រើការងារ',
    'organization':'អង្គភាព',
    'position':'មុខតំណែង',
    'department':'នាយកដ្ឋាន',
    'staff_type':'ប្រភេទមន្ត្រី',
    'rank_position':'ឋានៈស្មើរ',
    'office':'ការិយាល័យ',
    'framework_category':'ក្របខណ្ឌ',
    'salary_rank_group':'កាំបៀវត្ស',
    'salary_rank_type':'តំឡើងកាំបៀវត្សតាមរយៈ',
    'upgraded_salary_rank_at':'កាលបរិច្ឆេទតំឡើងកាំបៀវត្ស',
    'certificate_type':'សញ្ញាបត្រ',
    'major':'ជំនាញ',
    'graduated_at':'កាលបរិច្ឆេទបញ្ចប់ការសិក្សា',
    'prakas_number':'យោងប្រកាស-អនុក្រិត្យលេខ',
    'prakas_at':'ថ្ងៃចេញប្រកាស-អនុក្រិត្យលេខ',
    'skill':'ជំនាញ',
    'work_experience':'ប្រវត្តិការងារ',
    'work_experience_add':'បន្ថែមប្រវត្តិការងារ',
    'medals_add':'បន្ថែមឥស្សរយស',
    'medals':'ឥស្សរយស'
    // Layout ================================================
  };

  static String translate({
    String? key,
    Map<String, dynamic>? data,
    required String lang,
  }) {
    // Handle JSON-based translation if data is provided
    if (data != null) {
      final dataKey = lang == 'en' ? 'name_en' : 'name_kh';
      if (data.containsKey(dataKey) &&
          data[dataKey] is String &&
          (data[dataKey] as String).isNotEmpty) {
        return data[dataKey] as String;
      }
      return 'N/A';
    }

    // Handle static key-based translation if key is provided
    if (key != null) {
      if (lang == 'kh') {
        return _khmer[key] ?? 'N/A';
      } else {
        return _english[key] ?? 'N/A';
      }
    }

    // Return N/A if neither key nor data is provided
    return 'N/A';
  }
}
